export type RegionGroup = {
  label: string;
  districts: string[];
};

export type RegionGroups = {
  [province: string]: RegionGroup[];
};

// 인기 지역 (SearchBar 칩에 표시)
export const POPULAR_PROVINCES = [
  "서울",
  "경기",
  "인천",
  "부산",
  "제주",
  "강원",
  "대구",
  "대전",
];

// 야놀자 스타일 동네/역 기반 지역 그룹
// 각 그룹의 districts 배열 = DB region 필드에서 매칭할 구/군/시 이름
// 선택 시 "시/도 + 구/군" 형태로 selectedRegions에 추가 (예: "서울 강남구")
export const REGION_GROUPS: RegionGroups = {
  서울: [
    { label: "강남/역삼/삼성/논현", districts: ["강남구"] },
    { label: "서초/신사/방배", districts: ["서초구"] },
    { label: "잠실/방이", districts: ["송파구"] },
    { label: "잠실새내/신천/종합운동장", districts: ["송파구"] },
    { label: "영등포/여의도", districts: ["영등포구"] },
    { label: "신림/서울대/사당/동작", districts: ["관악구", "동작구"] },
    { label: "천호/길동/둔촌", districts: ["강동구"] },
    { label: "화곡/까치산/양천/목동", districts: ["강서구", "양천구"] },
    { label: "구로/금천/오류/신도림", districts: ["구로구", "금천구"] },
    { label: "신촌/홍대/합정", districts: ["마포구", "서대문구"] },
    { label: "연신내/불광/응암", districts: ["은평구"] },
    { label: "종로/대학로/동묘앞역", districts: ["종로구"] },
    { label: "성신여대/성북/월곡", districts: ["성북구"] },
    { label: "이태원/용산/서울역/명동/회현", districts: ["용산구", "중구"] },
    { label: "동대문/을지로/충무로/신당/약수", districts: ["중구", "동대문구"] },
    { label: "회기/고려대/청량리/신설동", districts: ["동대문구"] },
    { label: "장안동/답십리", districts: ["동대문구", "성동구"] },
    { label: "건대/군자/구의", districts: ["광진구"] },
    { label: "왕십리/성수/금호", districts: ["성동구"] },
    { label: "수유/미아", districts: ["강북구"] },
    { label: "상봉/중랑/면목", districts: ["중랑구"] },
    { label: "태릉/노원/도봉/창동", districts: ["노원구", "도봉구"] },
  ],
  경기: [
    { label: "수원 인계동/나혜석거리", districts: ["수원시"] },
    { label: "수원역/구운/행궁/장안구", districts: ["수원시"] },
    { label: "수원시청/권선/영통/세류", districts: ["수원시"] },
    { label: "안양/평촌/인덕원/과천", districts: ["안양시", "과천시"] },
    { label: "성남/분당/위례", districts: ["성남시"] },
    { label: "용인", districts: ["용인시"] },
    { label: "동탄/화성/오산/병점", districts: ["화성시", "오산시"] },
    { label: "하남/광주(퇴촌/곤지암)", districts: ["하남시", "광주시"] },
    { label: "여주/이천", districts: ["여주시", "이천시"] },
    { label: "안산 중앙역", districts: ["안산시"] },
    { label: "안산 고잔/상록수/선부동/월피동", districts: ["안산시"] },
    { label: "군포/의왕/금정/산본", districts: ["군포시", "의왕시"] },
    { label: "시흥(월곶/정왕/오이도/거북섬)", districts: ["시흥시"] },
    { label: "광명", districts: ["광명시"] },
    { label: "평택/송탄/안성", districts: ["평택시", "안성시"] },
    { label: "부천", districts: ["부천시"] },
    { label: "일산/고양", districts: ["고양시"] },
    { label: "파주", districts: ["파주시"] },
    { label: "김포", districts: ["김포시"] },
    { label: "의정부", districts: ["의정부시"] },
    { label: "구리", districts: ["구리시"] },
    { label: "남양주(다산/별내/와부/호평)", districts: ["남양주시"] },
    { label: "남양주(오남/조안/화도/진접)", districts: ["남양주시"] },
    { label: "포천", districts: ["포천시"] },
    { label: "양주/동두천/연천", districts: ["양주시", "동두천시", "연천군"] },
    { label: "양평", districts: ["양평군"] },
    { label: "가평/청평", districts: ["가평군"] },
    { label: "제부도/대부도", districts: ["화성시", "안산시"] },
  ],
  인천: [
    { label: "부평", districts: ["부평구"] },
    { label: "구월/소래포구/호구포", districts: ["남동구"] },
    { label: "서구(석남/서구청/검단)", districts: ["서구"] },
    { label: "계양(작전/경인교대)", districts: ["계양구"] },
    { label: "주안", districts: ["미추홀구"] },
    { label: "송도/연수", districts: ["연수구"] },
    { label: "인천공항/을왕리/영종도", districts: ["중구"] },
    { label: "동암/간석", districts: ["부평구", "남동구"] },
    { label: "용현/숭의/월미도/신포/동인천/연안부두", districts: ["미추홀구", "중구", "동구"] },
    { label: "강화/옹진", districts: ["강화군", "옹진군"] },
  ],
  부산: [
    { label: "해운대/센텀시티/재송", districts: ["해운대구"] },
    { label: "송정/기장/정관/오시리아 관광단지", districts: ["기장군"] },
    { label: "광안리/수영", districts: ["수영구"] },
    { label: "경성대/대연/용호동/문현", districts: ["남구"] },
    { label: "서면/양정/초읍/부산시민공원", districts: ["부산진구"] },
    { label: "남포동/중앙동/태종대/송도/영도", districts: ["중구", "영도구", "서구"] },
    { label: "부산역/범일동/부산진역", districts: ["동구"] },
    { label: "연산/토곡", districts: ["연제구"] },
    { label: "동래/사직/미남/온천장/부산대/구서/서동", districts: ["동래구", "금정구"] },
    { label: "사상(경전철)/엄궁/학장", districts: ["사상구"] },
    { label: "덕천/화명/만덕/구포(구포역/KTX역)", districts: ["북구", "강서구"] },
    { label: "하단/명지/김해공항/다대포/강서/신호/괴정/지사", districts: ["사하구", "강서구"] },
  ],
  대구: [
    { label: "동성로/서문시장/대구역/경북대/엑스코", districts: ["중구", "북구"] },
    { label: "동대구역/신천동/수성못/범어/라이온즈파크/알파시티/시지", districts: ["동구", "수성구"] },
    { label: "대구공항/혁신도시/동촌유원지/팔공산/이시아폴리스/군위", districts: ["동구", "군위군"] },
    { label: "서대구역/북부정류장/평리/비산/칠곡지구/동천동/금호지구", districts: ["서구", "북구"] },
    { label: "두류/이월드/본리동/죽전동/서부정류장/앞산공원/안지랑/대명동/봉덕동", districts: ["달서구", "남구"] },
    { label: "성서/계명대/상인동/대곡/현풍/테크노폴리스/가창/달성군", districts: ["달서구", "달성군"] },
  ],
  광주: [
    { label: "상무지구/금호지구/유스퀘어/서구", districts: ["서구"] },
    { label: "충장로/대인시장/국립아시아문화전당/동구/남구", districts: ["동구", "남구"] },
    { label: "첨단지구/양산동", districts: ["광산구"] },
    { label: "하남/광주여대/송정역/광산구", districts: ["광산구"] },
    { label: "광주역/기아챔피언스필드/전대사거리/북구", districts: ["북구"] },
  ],
  대전: [
    { label: "유성구", districts: ["유성구"] },
    { label: "중구(은행/대흥/선화/유천)", districts: ["중구"] },
    { label: "동구(용전/복합터미널)", districts: ["동구"] },
    { label: "서구(둔산/용문/월평)", districts: ["서구"] },
    { label: "대덕구(중리/신탄진)", districts: ["대덕구"] },
  ],
  울산: [
    { label: "남구/중구(삼산/성남/무거/신정)", districts: ["남구", "중구"] },
    { label: "동구/북구/울주군(일산/진장/진하/KTX역/영남알프스)", districts: ["동구", "북구", "울주군"] },
  ],
  세종: [],
  강원: [
    { label: "춘천/강촌", districts: ["춘천시"] },
    { label: "원주", districts: ["원주시"] },
    { label: "경포대/사천/주문진/정동진", districts: ["강릉시"] },
    { label: "강릉역/교동/옥계", districts: ["강릉시"] },
    { label: "영월/정선", districts: ["영월군", "정선군"] },
    { label: "속초/고성", districts: ["속초시", "고성군"] },
    { label: "양양(서피비치/낙산)", districts: ["양양군"] },
    { label: "동해/삼척/태백", districts: ["동해시", "삼척시", "태백시"] },
    { label: "평창", districts: ["평창군"] },
    { label: "홍천/횡성", districts: ["홍천군", "횡성군"] },
    { label: "화천/철원/인제/양구", districts: ["화천군", "철원군", "인제군", "양구군"] },
  ],
  충북: [
    { label: "청주 흥덕구/서원구(청주 터미널)", districts: ["청주시"] },
    { label: "청주 상당구/청원구(청주국제공항)", districts: ["청주시"] },
    { label: "충주/수안보", districts: ["충주시"] },
    { label: "제천/단양", districts: ["제천시", "단양군"] },
    { label: "진천/음성", districts: ["진천군", "음성군"] },
    { label: "보은/옥천/괴산/증평/영동", districts: ["보은군", "옥천군", "괴산군", "증평군", "영동군"] },
  ],
  충남: [
    { label: "천안 서북구", districts: ["천안시"] },
    { label: "천안 동남구", districts: ["천안시"] },
    { label: "아산", districts: ["아산시"] },
    { label: "공주/동학사", districts: ["공주시"] },
    { label: "계룡/금산/논산/청양", districts: ["계룡시", "금산군", "논산시", "청양군"] },
    { label: "예산/홍성", districts: ["예산군", "홍성군"] },
    { label: "태안/안면도", districts: ["태안군"] },
    { label: "서산", districts: ["서산시"] },
    { label: "당진", districts: ["당진시"] },
    { label: "보령/대천해수욕장", districts: ["보령시"] },
    { label: "서천/부여", districts: ["서천군", "부여군"] },
  ],
  전북: [
    { label: "전주 덕진구", districts: ["전주시"] },
    { label: "전주 완산구/완주", districts: ["전주시", "완주군"] },
    { label: "군산", districts: ["군산시"] },
    { label: "익산", districts: ["익산시"] },
    { label: "남원/임실/순창/무주/진안/장수", districts: ["남원시", "임실군", "순창군", "무주군", "진안군", "장수군"] },
    { label: "정읍/부안/김제/고창", districts: ["정읍시", "부안군", "김제시", "고창군"] },
  ],
  전남: [
    { label: "여수", districts: ["여수시"] },
    { label: "순천", districts: ["순천시"] },
    { label: "광양", districts: ["광양시"] },
    { label: "목포", districts: ["목포시"] },
    { label: "무안/영암/신안", districts: ["무안군", "영암군", "신안군"] },
    { label: "나주/함평/영광/장성", districts: ["나주시", "함평군", "영광군", "장성군"] },
    { label: "담양/곡성/화순/구례", districts: ["담양군", "곡성군", "화순군", "구례군"] },
    { label: "해남/완도/진도/강진/장흥/보성/고흥", districts: ["해남군", "완도군", "진도군", "강진군", "장흥군", "보성군", "고흥군"] },
  ],
  경북: [
    { label: "포항/남구(시청/시외버스터미널/구룡포/쌍사/문덕/오천/송도)", districts: ["포항시"] },
    { label: "포항/북구(영일대/죽도시장/여객터미널)", districts: ["포항시"] },
    { label: "경주(보문단지/황리단길/불국사/양남/감포/안강)", districts: ["경주시"] },
    { label: "구미", districts: ["구미시"] },
    { label: "경산(영남대/대구대/갓바위/하양/진량/자인)", districts: ["경산시"] },
    { label: "안동(경북도청/하회마을)", districts: ["안동시"] },
    { label: "영천/청도", districts: ["영천시", "청도군"] },
    { label: "김천/칠곡/성주", districts: ["김천시", "칠곡군", "성주군"] },
    { label: "문경/상주/영주/예천/의성/봉화", districts: ["문경시", "상주시", "영주시", "예천군", "의성군", "봉화군"] },
    { label: "울진/영덕/청송", districts: ["울진군", "영덕군", "청송군"] },
    { label: "울릉도", districts: ["울릉군"] },
  ],
  경남: [
    { label: "창원 상남동/용호동/중앙동/창원시청", districts: ["창원시"] },
    { label: "창원 명서동/봉곡동/팔용동/북면온천/창원종합버스터미널", districts: ["창원시"] },
    { label: "마산", districts: ["창원시"] },
    { label: "진해", districts: ["창원시"] },
    { label: "김해/장유", districts: ["김해시"] },
    { label: "양산/밀양", districts: ["양산시", "밀양시"] },
    { label: "진주", districts: ["진주시"] },
    { label: "거제/통영/고성", districts: ["거제시", "통영시", "고성군"] },
    { label: "사천/남해", districts: ["사천시", "남해군"] },
    { label: "하동/산청/함양", districts: ["하동군", "산청군", "함양군"] },
    { label: "거창/함안/창녕/합천/의령", districts: ["거창군", "함안군", "창녕군", "합천군", "의령군"] },
  ],
  제주: [
    { label: "제주공항 서부(용담/도두/연동/노형동)", districts: ["제주시"] },
    { label: "제주공항 동부(제주시청/탑동/건입동)/추자도", districts: ["제주시"] },
    { label: "서귀포시/중문/모슬포", districts: ["서귀포시"] },
    { label: "이호테우/하귀/애월/한림/협재", districts: ["제주시"] },
    { label: "함덕/김녕/세화", districts: ["제주시"] },
    { label: "남원/표선/성산", districts: ["서귀포시"] },
  ],
};
